### ISSUE TITLE
VgsInfoRule ignored on VGSEditText

### ISSUE THREAD

**Issue by marcoRS** [verygoodsecurity/android-sdk-demo#16]
Hello,  
         I am trying to use a `com.verygoodsecurity.vgscollect.widget.VGSEditText` to collect a pin number of length 4. I want to use a VgsInfoRule to set the limit to 4 using the following: 
         
```kotlin
val rule = VGSInfoRule.ValidationBuilder().apply {
            setAllowableMaxLength(4)
            setAllowableMinLength(4)
            setRegex("([0-9]{4})")
        }.build()

        pinEntryEditText.addRule(rule)
```        

This doesn't seem to work and I am able to enter a pin longer than 4.

**Comment by DmytroDm** [comment]
Duplicate of [issue](https://github.com/verygoodsecurity/vgs-collect-android/issues/413).
